trigger:
- none

pool:
  vmImage: ubuntu-latest

parameters:
- name: 'AutoRunMachine'
  type: object
  default: [
    10.10.10.1,
    10.10.10.2,
    10.10.10.3
  ]

stages:
  - stage: OpenRdpConnections
    displayName: Open RDP Connections
    jobs:
    - job: OpenConnections
      displayName: Open Connections
      steps:
        - ${{ each p in parameters.AutoRunMachine }}:
          - task: PowerShell@2
            displayName: Open RDP Connection to ${{ p }}
            inputs:
              targetType: 'inline'
              script: |
                Write-Host ${{ p }}
